name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with Google Cloud
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 3: Configure Google Cloud project
      - name: Configure Google Cloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region us-central1

      # Step 4: Deploy to Cloud Run
      - name: Deploy operator-service to Cloud Run
        run: |
          gcloud run deploy operator-service \
            --source . \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars=MONGO_URI_OPERATOR=${{ secrets.MONGO_URI_OPERATOR }},\
            PORT=8087,\
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }},\
            FROM_EMAIL=duvindudushan@gmail.com,\
            FROM_EMAIL1=info@em665.bussewaya.online,\
            MONGO_URI_AUTHENTICATION=${{ secrets.MONGO_URI_AUTHENTICATION }},\
            AUTHENTICATION_SERVICE_URL_LOCAL=http://localhost:8088/authentication-service/users,\
            AUTHENTICATION_SERVICE_URL_PRODUCTION=https://api.authenticationservice.bussewaya.online/authentication-service/users

